### ISSUE TITLE
Can't get geomate.php custom config to work

### ISSUE THREAD

**Issue by jayhlee** [vaersaagod/geomate#1]
I can't seem to get GeoMate to work in my setup. For my site, I'm using [craft3-multi-environment](https://github.com/nystudio107/craft3-multi-environment) configurations. I've successfully downloaded GeoMate and downloaded the geolocation database, but none of the GeoMate variables are working. (e.g. `craft.geomate.country`, `craft.geomate.countryCode`). 

Based on the docs, I have a feeling the source of the issue is the geomate.php config file I created and added to the Craft config folder. I have the following configs, but it doesn't seem to take. In fact, the config settings just show up at the top of my web pages above my _layout.twig.

```
'forceIp' => 'IP-NUMBER-HERE',

'autoRedirectEnabled' => true,

'redirectMap' => [
    'korean' => 'ko',
    'global' => '*'
]
```
I'm pretty sure this is a user error on my end. But just in case, I was thinking it could possibly be an issue with the craft3-multi-environment set up I have. Any guidance would be greatly appreciated. Thanks much!

**Comment by aelvan** [comment]
Sounds like you didn't create the config file correctly. It's suppose to be a php file that returns an array, either with the config settings as keys, or with the config settings nested inside keys for environment. So, something like:

```
<?php

return [
    '*' => [
        'forceIp' => 'IP-NUMBER-HERE',

        'autoRedirectEnabled' => true,

        'redirectMap' => [
             'korean' => 'ko',
             'global' => '*'
        ]
    ]
];
```

Also note that if you're logged in as an admin, by default you won't be redirected. So either test in incognito mode, or toggle `redirectIgnoreAdmins` in your config.
