### ISSUE TITLE
Error Undefined index: HTTP_ACCEPT_LANGUAGE when using redirectMapSimpleModeKey => language

### ISSUE THREAD

**Issue by harispepic** [vaersaagod/geomate#10]
Hello,

When I switch `redirectMapSimpleModeKey` to `language` some bots cannot access the page, the following error occurs:
`2019-07-02 10:33:27 [-][-][b0b9cbc6df7eb8d9cde749fb1237c255][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: HTTP_ACCEPT_LANGUAGE in /public_html/domain.xyz/vendor/vaersaagod/geomate/src/helpers/GeoMateHelper.php:68`

Could you help me here out?

Regards

**Comment by aelvan** [comment]
Should be fixed in v1.0.5. Thanks for reporting!

**Comment by harispepic** [comment]
Thanks for fixing! 🎊
