### ISSUE TITLE
Retrieve list of all countries in database

### ISSUE THREAD

**Issue by amityweb** [vaersaagod/geomate#11]
How do we fetch a list of all the countries in the database, and their values like country codes? 

Two reasons... 

1) For the mapping we need to know what the country codes are to map to our sites.

2) We actually have a contact form where a user chooses their country. I would like that country automatically chosen. So the country list needs to be all the countries in the database. 

So how can we get this list? 

Thanks!

**Comment by aelvan** [comment]
Hi,

It's not possible to query the Maxmind database for countries, it's strictly for ip lookups. 


The isoCode property on Country follows the ISO-3166-1 two-letter standard (https://en.m.wikipedia.org/wiki/ISO_3166-1), so you can get a list of countries that follows that standard from anywhere, and use that.

**Comment by amityweb** [comment]
So we have to manually add the countries into a field or something? OK. 

We are using Commerce on this site, so I have managed to fetch all the Commerce sites which seem to  be the same list.
