### ISSUE TITLE
Auto creation of redirectMap

### ISSUE THREAD

**Issue by amityweb** [vaersaagod/geomate#12]
How can we have the redirectMap auto created based on the sites we already have setup? If my customer creates a new site, I dont want to have to manually add it to the config, when the config array would just replicate the Sites list. Our site handles are the same as the country codes you see. 

Here are our sites country codes in an array, then the config array we need to create. Identical. 

```
'ourSitesInAnArray' => [
    'ua' => 'us',
    'ca' => 'ca',
    'au' => 'au' 
]
```

```
'redirectMap' => [
    'ua' => 'us',
    'ca' => 'ca',
    'au' => 'au' 
]
```

So ideally just create redirectMap from the Sites. 

It would be great to then override it, so we can add in:
`redirectMap['uk'] = 'gb';`

**Comment by amityweb** [comment]
Just reread this so I think it does it by default but can we override it with one country like I mentioned? I will try to test it but my other issue prevents me fully testing it. 
“By default, it's assumed that the value is the detected country code”

**Comment by aelvan** [comment]
If a new site is created, you'll have to add the necessary configuration to the config file, there's no way to automatically generate that. The config file is just PHP though, so you could just query Craft and generate the array inside the config file. That's a bit beyond the scope of this repo, I suggest asking for help on SE or Discord if you need it.
