### ISSUE TITLE
Is there a way to overwrite autoRedirectEnabled value

### ISSUE THREAD

**Issue by Geestig** [vaersaagod/geomate#15]
Whenever I configurate autoRedirectEnabled to be true I get the correct results. However the issue is that users can't change to another language manually. Is there a way to allow this while keeping the first visit redirect to the correct language?

**Comment by aelvan** [comment]
By `...users can't change to another language manually...` what do you mean exactly? If you provide links where the user can switch to another language, you need to pass the links through the `addOverrideParam` twig filter to indicate to GeoMate that the user has manually selected the language.

**Comment by Geestig** [comment]
that was it, thx for the quick response. must've missed it!
