### ISSUE TITLE
Direct URL on different site redirects to home page of preferred site, not equivalent page

### ISSUE THREAD

**Issue by amityweb** [vaersaagod/geomate#17]
If I switch to a different country, so my site preference is set, and then go direct to a URL on a different site, I get redirected to my preferred site home page, whereas actually I would exepect it to redirect to the equivalent page I was on. 

1) Go to www.myhomepage.com
2) Change to say FR, www.myhomepage.com/fr/?__geom=✪
3) Click a link or change URL to www.myhomepage.com/whateverpage
4) I get redirected to www.myhomepage.com/fr/ and NOT www.myhomepage.com/fr/whateverpage

Although this only works if the slugs are all the same, if the slugs are foreign it goes to a 404 anyway. I dont suppose you can guess a site URL from the foreign slug and do a redirect to the page without the country code? 

Thanks

**Comment by aelvan** [comment]
This is the intended behaviour, GeoMate will not try to guess URLs. 

If you have certain template routes that you don't want to automatically redirect for, use `redirectIgnoreUrlPatterns`. If you only want to redirect if a matching element exists, use `redirectMatchingElementOnly`. And if you have a need for more advanced logic, turn off `autoRedirectEnabled`, use `craft.geomate.redirectInformation()` to roll your own logic.
