### ISSUE TITLE
Changes to GeoLite 2 Free Downloadable Databases

### ISSUE THREAD

**Issue by cavellblood** [vaersaagod/geomate#21]
I tried updating the databases and got the following message

> An error occured! Please check your settings and try again.

I thought maybe it was a permissions issue. I finally tried visiting http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz and got an error: 
> geolite.maxmind.com’s server IP address could not be found.

So then I did a Google search and found these links that might be relevant:
- https://dev.maxmind.com/geoip/geoip2/geolite2/
- https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

Some pertinent information from that last link:

> Starting December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL. See the section below for steps on how to migrate to the new download mechanism.
> 
> **GeoLite2 Databases Affected**
> 
> - GeoLite2 Country
> - GeoLite2 City
>-  GeoLite2 ASN
>
> **Steps for Migration**     
>
> - Sign up for a MaxMind account (no purchase required)
> - Set your password and create a license key
> - Setup your download mechanism by using our GeoIP Update program or creating a direct download script

I haven't tried setting up a MaxMind account yet (going to here shortly) but I'm guessing that once I do I should be able to get a new link and I could used that link in the GeoMate config.php file. I'll report back here with any updates.

**Comment by cavellblood** [comment]
I had some trouble signing up. I signed up and waited for a while and didn't receive the email for  (just received it as I write this sentence, 16 minutes after signing up. I thought something went wrong when I submitting the form.) a long time. I was able to bypass waiting for that email by clicking on the account/user icon and clicking on the forgot password link and getting in that way. YMMV.

Anyway, after setting up an account with them and creating a license key I was able to use the instructions here: https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads to create a direct download script/link that looks something similar to this one:

`https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=XXXXXXXXXXXXg1fv&suffix=tar.gz`

Following that link downloaded a file named `GeoLite2-Country_20200107.tar.gz` which had the following files:

- COPYRIGHT.txt
- GeoLite2-Country.mmdb
- LICENSE.txt

I'm going to try to see if putting the direct download link above, with my license key in it, in the `geomate.php` config file will work now. I guess I'll have to get links for both the City and Country databases.

**Comment by cavellblood** [comment]
So I was able to update my `geomate.php` config file to the following and it successfully downloaded the databases:

``` php
<?php

return [
	'*' => [
		'countryDbDownloadUrl' => 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=XXXXXXXXXXXX&suffix=tar.gz',
		'cityDbDownloadUrl' => 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=XXXXXXXXXXXX&suffix=tar.gz'
	],
	/* ... */
];
```

For anyone reading this, you'll need to replace the `license_key=XXXXXXXXXXXX` with your license key from your MaxMind account.

Having said that, I don't know if this is the way that the developer is going to suggest that we all move forward with when using this plugin or if there will be an alternate method that will be implemented in a future plugin update.

**Comment by cavellblood** [comment]
I moved the GeoLite license key to the `.env` file so now my config file looks like this:

``` php
<?php

return [
	'*' => [
		'countryDbDownloadUrl' => 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=' . getenv('GEOLITE_LICENSE_KEY') . '&suffix=tar.gz',
		'cityDbDownloadUrl' => 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=' . getenv('GEOLITE_LICENSE_KEY') . '&suffix=tar.gz'
	],
	/* ... */
];
```

I've confirmed that this configuration works locally with the benefit of not having the license key stored in git.

**Comment by cavellblood** [comment]
And this also worked in production. Keeping this issue open so others may see it until the developer is able to notify others of this issue.

**Comment by aelvan** [comment]
Thanks for looking into this and providing such a thorough rundown of what you found. I saw the announcement from Maxmind before Christmas, but hadn't had time to look into it yet.

I've push a new release now that removes the old download URLs, shows an error message in the utility if the paths are not configured, and added a notice and explanation in the README and CHANGELOG on how to get the new URLs.

**Comment by cavellblood** [comment]
Looks great! Thank you, @aelvan!
