### ISSUE TITLE
The MaxMind DB file's search tree is corrupt

### ISSUE THREAD

**Issue by cavellblood** [vaersaagod/geomate#22]
So I'm using `v1.1.0` and I'm getting this error in the Craft logs:

> Database read error (InvalidDatabaseException) :: The MaxMind DB file's search tree is corrupt

I've removed the old databases and re-downloaded the new ones from the new URL setup and still getting the same results.`cacheEnabled` is set to `false` in my config file.

Any ideas?

**Comment by cavellblood** [comment]
Here's a preview of the logs:

<img width="1314" alt="Screen Shot 2020-01-07 at 3 27 57 PM" src="https://user-images.githubusercontent.com/727740/71930976-5b81a300-3162-11ea-840c-0282a3b4938d.png">

**Comment by aelvan** [comment]
Seeing the same with the new db, I'll investigate.

**Comment by aelvan** [comment]
The issue seems to be those extra files which the gz file now contains. The way I extracted the data adds everything to one file. I have to continue trying to find a solution tomorrow. 

In the meantime, downloading the gz file manually, extracting the .mmdb files, and placing them in the `dbPath` manually, should work as a stop-gap solution.

**Comment by aelvan** [comment]
And if anyone has some tips on how to extract all files from a .tar.gz file, let me know. ;)

**Comment by cavellblood** [comment]
Excellent. I'll try manually placing the files in the `dbPath`. Thanks.

**Comment by cavellblood** [comment]
That fixed it for me for the meantime. I'll just make sure not to update the database from the plugin. Thanks!

**Comment by aelvan** [comment]
This was fixed in v1.1.0.1.

**Comment by danethomas** [comment]
I've recently upgrade my MaxMind DB and I'm seeing this error 

2021-03-25 20:20:34 - error - geomate
Database read error (InvalidDatabaseException) :: The MaxMind DB file's search tree is corrupt
