### ISSUE TITLE
redirectIgnoreUrlPatterns for subdomains or site handles

### ISSUE THREAD

**Issue by nomadic-code** [vaersaagod/geomate#24]
Hello, I currently have a localized site with redirectMap setting shown below. I recently added a fourth site in Craft to serve content to a subdomain, however the redirectMap is redirecting all requests to the subdomain based off of the redirect settings. Is there a way to ignore the subdomain and/or site handle?

'redirectMap' => [
        'au' => [
            'continent' => ['au', 'oc'],
        ],
        'uk' => [
            'continent' => 'eu',
        ],
        'default' => '*',
    ],

**Comment by aelvan** [comment]
Hi,

Ok, so you have some sites where you want to use the redirect functionality, but you have one where you don't want to redirect at all?

Hadn't thought about that scenario, I must admit. :) You could use PHP in your config file to enable/disable geomate, or manipulate the redirectMap, but I'm open adding some way of disabling it in a prettier way through the config. How do you envision that this should work? Would an array of site handles in a config setting work? Or maybe by site group? Or maybe `autoRedirectEnabled` could either be a boolean like now, but also an array of enabled sites?

**Comment by nomadic-code** [comment]
I did not even realize I could disable in the config file, I should have thought to look for something like that...
I should also say thank you for an awesome (and free!) plugin, regardless of what comes of this discussion, and thank you for responding so quickly to my post.

For site groups vs site handles, I would think site handles would give more power to the user in the event that site groups are not organized efficiently or something. Enabled sites is also an interesting thought; I had only thought of it from the exclusion perspective. For my specific use case, being able to exclude a site would be more efficient than tracking which sites should be included as the number of sites that I need to exclude is just the one out of a current four

**Comment by chadcrowell** [comment]
+1 on this. My current redirectMap is 

```
'redirectMap' => [
            'store' => 'us',
            'www' => '*',
        	],
```

So, visitors from the US are sent to the "store" site, and everyone else is sent to the "www" site. We're launching a customer portal that needs to be accessible from all countries, so being able to exclude the "customers" site from any redirection would be great.  Something like:

```
'redirectExclude' => ['customers','otherSiteHandle'],
'redirectMap' => [
            'store' => 'us',
            'www' => '*',
        	],
```

**Comment by aelvan** [comment]
I added a `autoRedirectExclude` config setting in v1.2.0 which should address this issue.
