### ISSUE TITLE
redirectMatchingElementOnly not working as expected

### ISSUE THREAD

**Issue by Thomas-b-wm** [vaersaagod/geomate#25]
Hi, in a current project where we want to use geomate, i use this option and expected, that there will be no redirect to a 404, if an entry in a target-site(language) doesn't exist.
No matter if the current section is enabled for the target-site or not.

For example:
My section is enabled for english, spanish and frensh sites (SiteID 1-3)
My testentry is configured as this:
www.domain.com/testentry --> enabled
www.domain.com/es/testentry --> entry disabled for spanish site
www.domain.com/fr/testentry --> enabled

If i enter the root-page-url with a frensh IP, i get redirected 
(www.domain.com/ ---> www.domain.com/fr/). 
Spanish IP will do the same 
(www.domain.com/ ---> www.domain.com/es/)
Fine.

If i enter the testentry-url with spanish ip, i get redirected correctly
(www.domain.com/testentry ---> www.domain.com/es/testentry).
But if i enter with a frensh IP, i also get redirected 
(www.domain.com/testentry ---> www.domain.com/fr/testentry). 
This ends up in a 404. This should not happen i think.

After debugging the plugin, i found the "getElementById" usage.
If i extend the function like this:

     
     $enabledSites = Craft::$app->getElements()->getEnabledSiteIdsForElement($currentElement->id);
     if ($elementMatchOnly && !in_array($site->id, $enabledSites)) {
         $url = '';
     }

the behaviour is as expected, no redirect for the frensh Url.
Seems to be a bug, because i can not find any misconfiguration.

**Comment by aelvan** [comment]
Thanks for reporting. The `redirectMatchingElementOnly` was meant to deal with elements vs routes, so I hadn't actually thought of the case where elements were disabled in some sites. But, especially in light of the naming, it makes sense that it should take this into account. It was fixed in v1.2.0.
