### ISSUE TITLE
Downloading the geolocation database URL's incorrect?

### ISSUE THREAD

**Issue by jderdock** [vaersaagod/geomate#27]
in the docs, under "Downloading the geolocation database URL's", there are two URL's listed. 

The cityDbDownloadUrl has the license key placeholder wrapped in back tick/grave accent, but countryDbDownloadUrl doe not. Removing the back ticks/grave accents worked for me.

```
'countryDbDownloadUrl' => 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz',
'cityDbDownloadUrl' => 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=`YOUR_LICENSE_KEY`&suffix=tar.gz',
```

**Comment by aelvan** [comment]
Yes, the backticks was a typo, it's fixed now.
