### ISSUE TITLE
Does not work with Blitz

### ISSUE THREAD

**Issue by lenvanessen** [vaersaagod/geomate#29]
Apparantly, blitz intercepts the request before geomate does, disabeling Geomate's functionality.

Might be a chicken-egg situation on which plug-in causes it, but it would be great if it can be resolved.

https://github.com/putyourlightson/craft-blitz/issues/189

**Comment by aelvan** [comment]
Yeah, both Blitz and GeoMate listens to `Application::EVENT_INIT` and does its thing there, so it's basically a race condition without any solution AFAIK.

**Comment by bencroker** [comment]
Blitz was firing even before `Application::EVENT_INIT` but I actually just moved it to see if I could make it work with Geomate, however Craft loads plugins in alphabetical order, so no cigar. I'll continue looking into whether there's a workaround.

**Comment by bencroker** [comment]
According to the Yii docs:

> To insert the new handler at the start of the handler queue so that the handler gets called first, you may call yii\base\Component::on(), passing false for the fourth parameter.
https://www.yiiframework.com/doc/guide/2.0/en/concept-events#event-handler-order

So you could implement this in Geomate, but it's unfortunately not something I can do in Blitz. Thoughts @aelvan?

**Comment by aelvan** [comment]
Nifty, I'll implement!

**Comment by aelvan** [comment]
@lenvanessen Try updating to 1.2.1 and see if that fixes the issue.

**Comment by bencroker** [comment]
FYI you’ll need to use the develop branch of Blitz to verify this.

-Ben
