### ISSUE TITLE
Don't show MaxMind DB Warning if browser language is used

### ISSUE THREAD

**Issue by urbantrout** [vaersaagod/geomate#32]
I use this extension for browser based redirects only. Would be nice if the following 2 warnings would not show up if the plugin is configured to only use browser based redirects.

- **Database download URLs have not been configured.**
- **No database found! Please check the settings below, and download the GeoIP2 databases.**

**Comment by aelvan** [comment]
Well, there're other ways to use the database apart from redirects, which would need a database present. I'm unsure if there's universal formula for anticipating if the database is needed or not, so I think we'll keep the warning to avoid extra support because people haven't downloaded it.
