### ISSUE TITLE
Option to redirect user only once

### ISSUE THREAD

**Issue by Stalex89** [vaersaagod/geomate#33]
I have a website with a multi-site setup.

Currently, there is an option to enable automatic redirects of users to sites based on the redirectMap config setting.

In my case, I need my user to be redirected only once they enter the homepage, and after that then they can switch the language if they need, and they will not be redirected.

But for me now it redirects automatically whenever I go to some page, even if I switch the language on the website or type language site handler ('/es').

Is there a possibility to set the redirection only once, or set automatioc redirection only on a base url ('www.site.com')and exclude all urls with site handlers ('www.site.com/es') from automatic redirection? Thank you in advance.

geomate.php
`<?php
    return [
    'redirectIgnoreAdmins' => false,
    'autoRedirectEnabled' => true,
    'redirectMap' => [
        'nl' => ['nl','NL'],
        'uk' => ['uk','UK'],
        'de' => ['de','DE'],
        'es' => ['es','ES'],
        'en' => '*'
    ]
];`

My multi-site conf 
![Schermafbeelding 2020-07-01 om 12 03 53](https://user-images.githubusercontent.com/23526237/86231529-fd72cd00-bb92-11ea-9e3a-c52983db9df9.png)

**Comment by aelvan** [comment]
This is what the override param is for, see the example for [getSiteLinks](https://github.com/vaersaagod/geomate#craftgeomategetsitelinks) on how to use it.

**Comment by Stalex89** [comment]
Thank you for the response, that was helpful!
