### ISSUE TITLE
redirectIgnoreUrlPatterns not working for auto redirect

### ISSUE THREAD

**Issue by Stalex89** [vaersaagod/geomate#34]
I have a website with a multi-site setup

I need a plugin to auto redirect only for the base url (*.example.com) with subdomains and ignore any other urls (including the one with language handles)

For that I'm trying to use redirectIgnoreUrlPatterns param with passing a regex to it

`^(.*example\.com\/.*.$).*$`

![Schermafbeelding 2020-07-06 om 14 51 15](https://user-images.githubusercontent.com/23526237/86595523-24693e80-bf99-11ea-93c8-2b47b31665cb.png)

So the one highlighted with green should be ignored for auto redirection

![Schermafbeelding 2020-07-06 om 14 59 12](https://user-images.githubusercontent.com/23526237/86595823-95a8f180-bf99-11ea-8694-ac3cfa5722ad.png)

However the plugin does not ignore those urls for some reason and keeps auto redirecting them.
Is there something I do wrong ?

**Comment by aelvan** [comment]
The pattern only matches the path, not the whole URL. Try removing the domain part and see if that helps.

**Comment by Stalex89** [comment]
I tried to apply the following regex:

![Schermafbeelding 2020-07-14 om 11 42 55](https://user-images.githubusercontent.com/23526237/87410900-35343880-c5c7-11ea-80d2-65cfb82513ce.png)

so now it should have matched the path (everything excluding the domain url and full url), but still it doesn't work for me.

**Comment by Stalex89** [comment]
@aelvan I've managed to solve the thing by the following regex:
`
^.+$
`
which means to ignore any path except empty path, which means the domain
A bit confusing but worked for me
Thank you for the hint!
