### ISSUE TITLE
Does this work with Cloudflare?

### ISSUE THREAD

**Issue by amityweb** [vaersaagod/geomate#38]
When using Cloudflare, the visitors IP on the server is Cloudflares. 

So therefore will this plugin work, or any additional work needed to get it to work? 

Thanks

**Comment by aelvan** [comment]
Haven't tested it myself, but I assume it will. GeoMate uses Craft's `getUserIP` method on the `Request` service. It checks some commonly used HTTP headers for forwarded IP information before using the actual IP of the request, and I assume that Cloudflare uses one of thise.

See:
https://github.com/craftcms/cms/blob/main/src/web/Request.php#L61
https://github.com/craftcms/cms/blob/main/src/web/Request.php#L1107

**Comment by amityweb** [comment]
I should have updated this, I forgot! 

We have been using this plugin with Cloudflare for a couple if weeks, and we have not had any issues, I think its working fine.
