### ISSUE TITLE
Should Geomate read and redirect based on GeoMateRedirectOverride cookie?

### ISSUE THREAD

**Issue by danethomas** [vaersaagod/geomate#39]
More of a question asking about the default or recommended behaviour. 

I've got a site switcher that makes use of the `addOverrideParam` and this sets the `GeoMateRedirectOverride` cookie with value. If a user was to visit the site again (before the cookie expired) should they automatically be directed to what's set in the cookie? 

Does GeoMate handle this or should this be done via a regular direct in the index template?

Thanks.

**Comment by aelvan** [comment]
If `autoRedirectEnabled` is enabled and applicable for the session, GeoMate should automatically redirect to the site selected in the site switcher, yes. Have you tested it and it's not working as expected?

**Comment by danethomas** [comment]
@aelvan thanks for the reply. I think my development 'forceIP' was playing a factor here. Pushed up onto a staging site and everything looks to be working as expected.
