### ISSUE TITLE
Allow disabling override paramter value completely

### ISSUE THREAD

**Issue by architchandra** [vaersaagod/geomate#41]
It might be a good idea to do away with the need to set a value to the override parameter, or at least allow setting it to `null`, so that the resulting URL can be cleaner eg.` xyz.com/?switch-lang`.

Setting `paramValue` to null currently leads to a URL like `xyz.com/?switch-lang=`.

**Comment by aelvan** [comment]
Thanks for your suggestion, but this won't be changed. Removing the query string altogether would lead to overriding not working in some scenarios, and empty query string parameters could be removed in some scenarios. The end goal (clean URLs) doesn't match up to that.

**Comment by rungta** [comment]
> empty query string parameters could be removed in some scenarios

What scenarios are these @aelvan?

**Comment by aelvan** [comment]
Proxies sorting and removing query string parameters to increase cache hits.
