### ISSUE TITLE
Macro "copyTextField" is not defined in template "_includes/forms".

### ISSUE THREAD

**Issue by Odusanya** [vaersaagod/geomate#43]
How to recreate:
Click on the Geomate tab, from the Utilities page
<img width="592" alt="image" src="https://user-images.githubusercontent.com/22182946/128757556-75fd484c-a2e1-4458-a5ac-f78d6db579b3.png">

Screenshot
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/22182946/128757085-68731038-8cbc-4d3d-957d-020ff25c2e2c.png">

Version
CraftCMS version: `3.3.20.1`
Geomate version: `1.3.1.1`

**Comment by aelvan** [comment]
Thanks for reporting, that macro was introduced in 3.6, shouldn't have been used without bumping requirements. Fixed in 1.3.1.2.
