### ISSUE TITLE
Site Groups

### ISSUE THREAD

**Issue by nathansnelgrove** [vaersaagod/geomate#47]
How would I configure Geomate to work within site groups that have the same language codes?

i.e. I have 2 sites, each with the same 2 languages. I have set them up in Site Groups so SEOMatic will do its magic. I need a way to make sure that Site B never redirects to Site A when it's redirecting based on an IP address. Is there some sort of config that I can tap into within Geomate to make that possible? If there is, I'm not sure what I'm missing or how I should set it up...

Thank you.

**Comment by aelvan** [comment]
There's no functionality in GeoMate that takes site groups into account. Haven't used SEOmatic, so not sure what logic/meaning it infers from them, but from the Craft side there is none. 

But you could probably roll your own redirect logic using the provided template methods, unless you turn `autoRedirectEnabled` on, GeoMate won't redirect users automatically.

**Comment by nathansnelgrove** [comment]
Thanks André, much appreciated. SEOMatic uses the groups to figure out what language attributes belong to which site (not that it matters in the context of this conversation). I appreciate you pointing towards the template methods. I’ll see if I can figure that out. Cheers!
