### ISSUE TITLE
Issue when behind NordVPN

### ISSUE THREAD

**Issue by simonda86** [vaersaagod/geomate#59]
Hi, I'm having an issue with this plugin running version `v1.3.1.2` on Craft CMS 3. It works fine for me even when I connect to my VPN, but an error is returned when my client is visiting the site.

![image](https://github.com/vaersaagod/geomate/assets/495114/47488f7d-1145-4fc1-bbe0-8800a9cb4d96)

**Comment by mmikkel** [comment]
Hi @simonda86,

What is `cacheDuration` set to in your `config/geomate.php` file? It should be either an integer (seconds) or a valid [duration interval string](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by simonda86** [comment]
Hi @mmikkel 

It's currently set to `P7D` which I think is a valid duration interval string?

**Comment by mmikkel** [comment]
Thanks. `P7D` is valid, looks like that value isn't being converted to an integer of seconds as expected by the cache service.

I'll look into this ASAP; for a quick fix you can change `cacheDuration` in `config/geomate.php` to `604800`, which should eliminate that exception.

**Comment by aelvan** [comment]
This has been fixed for both the Craft 3 and 4 versions.
