### ISSUE TITLE
web.log is flooded with warnings related to getMatchedElement()

### ISSUE THREAD

**Issue by jsunsawyer** [vaersaagod/geomate#6]
`[warning][craft\web\UrlManager::getMatchedElement] craft\web\UrlManager::getMatchedElement() was called before the application was fully initialized.`

See: https://docs.craftcms.com/api/v3/craft-web-urlmanager.html#public-methods

**Comment by aelvan** [comment]
Thanks for reporting, a fix has been push in v1.0.3.
