### ISSUE TITLE
3.0.0-beta.1 - error when used with commerce 5

### ISSUE THREAD

**Issue by stanislavprokopov** [vaersaagod/geomate#60]
Setup:
 - Craft 5.2.0
 - Commerce 5.0.10
 - GeoMate 3.0.0-beta.1

Add `{{ dump(currentUser.getPrimaryBillingAddress()) }}` to `templates/index.twig`

Now open homepage, result:

```
Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)
Calling unknown method: craft\elements\User::getPrimaryBillingAddress()
```

Now if you disable GeoMate and check the same page you will not get any errors but will get `null` as you are not authenticated.

It appears that the `CustomerBehavior` registered by `Commerce` plugin is missing for some reason.

Disabling this part in RedirectService makes it work again:

```
if ($this->shouldIgnoreUser()) {
            GeoMate::log('Redirect ignored because of user credentials (user is either an admin or in a usergroup that was configured to be ignored).', Logger::LEVEL_INFO);
            return null;
        }
```

I would guess its related to init order, calling `getIdentity()` caches the user object before commerce registers the behavior so when user is used in tpl it is missing the required methods and causes the error, changing 

```
Craft::$app->on(Application::EVENT_INIT, function() {
            $this->redirectCheck();
        }, null, false);
```

to

```
Craft::$app->on(Application::EVENT_INIT, function() {
            $this->redirectCheck();
        }, null, true);
```

or

```
Craft::$app->onInit(function() {
$this->redirectCheck();
});
```

Fixes the issue, but I am not sure how it affects other parts of the plugin.

**Comment by mmikkel** [comment]
Thanks for reporting that. 

I just tagged GeoMate v. 3.0.0-beta.2 (Craft 5) and v. 2.1.3 (Craft 4) with a fix for this issue.
