### ISSUE TITLE
Allow multiple countries to redirect to the same site

### ISSUE THREAD

**Issue by jsunsawyer** [vaersaagod/geomate#7]
We have a multi-site setup where each site represents a language/location.

Currently, we can set up our redirectMap with rules for each site.

What we want to do is add some additional settings for countries that aren't set up yet (or never will be) and redirect them to another site (one that already has its own redirect set).

Example:

```
'redirectMap' => [
    'de_ch' => [
        'country' => 'ch',
    ],
    'de_de' => [
        'country' => ['de', 'at']
    ],
    'us' => [
        'country' => 'us'
    ],
    'global' => '*'
]
```

Here, we'd want any user whose `country` is in `de` or `at` to be directed to our `de_de` site.

This might not account for more complex combinations of detection settings that some users may require, but would at least allow us to have a bit more control.

**Comment by aelvan** [comment]
Can't believe I didn't think of this use-case, thanks for making me aware of it. Added support for using arrays as values in the redirect map in 1.0.4.
