### ISSUE TITLE
Problems with segments

### ISSUE THREAD

**Issue by francescomugnai** [vaersaagod/geomate#9]
Hello,

first of all, thank you for this great plugin. It's fantastic!
I think I've a problem with the segments.

This is the situation: I've a site (not yet online) with 2 languages.

- **case 1:** _example.com/room_
If i pick one of the two languages I get redirect to the homepage (and not to the same page, translated, as expected).
The url I get is something like: example.com/en?__geom=✪

- **case 1:** _example.com/room/test_
it works like a charm. I can switch between the translated versions of the same page
The url I get is something like: example.com/en/room/test?__geom=✪

My link is simple as this:

```
<li>
       <a href="{{ siteLink.url | addOverrideParam }}">
           {{ siteLink.site }}
       </a>
</li>

```

My geomate.php file is like this:

```
return [
    'autoRedirectEnabled' => true,
    'redirectIgnoreAdmins' => false,
    'redirectMap' => [
        'italiano' => 'it',
        'inglese' => '*' 
    ]
];
```

What do you think? Can you please help me?
Thank you!

**Comment by aelvan** [comment]
Hi, sorry for the late reply, overlooked this. Is `example.com/room` the route to an entry (or other element), or is it just a template path?

**Comment by millerone** [comment]
Ciao André, thank you for your reply!
It's a template path.

My scenario is:

- entries -> fine
- template paths -> not working

Thanks!

**Comment by aelvan** [comment]
Right, that's the intended behavior. Geomate will only know what the url for the other sites are, if the current template has an element with an url for the other sites. If not, it'll fall back to linking to the frontpage of the other sites.

You can either do some conditionals and manually output the urls for template paths, or use singles instead of template paths. I reccommend the last, it's much more flexible.

**Comment by amityweb** [comment]
Same issue here, so I did this, but what happens now is the GeoMate cookie is never dropped. So I get my language select popup continuously. __geom=✪ is in the URL. 

Its as if the entry is missing the cookie does not get created or something? 

```
{% if entry is not defined %}
	
	{% set targetUrl =  siteUrl(craft.request.getPath(), siteId=redirectInfo.site.id) %}
	{% set currentUrl =  siteUrl(craft.request.getPath(), siteId=currentSite.id) %}

{% else %}
	
	{% set targetUrl = redirectInfo.url %}
	{% set currentUrl =  currentSite.baseUrl %}

{% endif %}

```

Full code:

```
{% set redirectInfo = craft.geomate.redirectInformation() %}

{% if redirectInfo %}
	
	{% set targetSiteSettings = craft.app.globals.getSetByHandle('siteSettings', redirectInfo.site.id) %}
	{% set currentSiteSettings = craft.app.globals.getSetByHandle('siteSettings', currentSite.id) %}
	
	{% set currentCountryFlag = currentSiteSettings.countryFlag.first() %}
	{% set targetCountryFlag = targetSiteSettings.countryFlag.first() %}
	

	<div class="reveal" id="countryRedirectPopup" data-reveal>

		<p>{{ strings('Please select the country version of the website you would like to view')}}</p>
		
		<br/>

		{% if entry is not defined %}
			
			{% set targetUrl =  siteUrl(craft.request.getPath(), siteId=redirectInfo.site.id) %}
			{% set currentUrl =  siteUrl(craft.request.getPath(), siteId=currentSite.id) %}
		
		{% else %}
			
			{% set targetUrl = redirectInfo.url %}
			{% set currentUrl =  currentSite.baseUrl %}
		
		{% endif %}
		
		<a href="{{ targetUrl | addOverrideParam }}"><img src="{{ targetCountryFlag.url }}" width="30" height="20">  {{ redirectInfo.site.name }}</a>
		
		<br/>
		<br/>
		
		<a href="{{ currentUrl | addOverrideParam }}"><img src="{{ currentCountryFlag.url }}" width="30" height="20"> {{ currentSite.name }}</a>
		
		<br/>
		<br/>
		
		<img src="/assets/img/logo" width="200" height="49">

		<button class="close-button" data-close aria-label="Close modal" type="button">
			<span aria-hidden="true">&times;</span>
		</button>

	</div>


{% endif %}
```

**Comment by aelvan** [comment]
This had nothing to do with the original issue, but it looks like you always showed the popup, there's no conditional to check if the user already has selected a site (ie, `craft.geomate.isOverridden()`). `craft.geomate.redirectInformation()` will always return information about what site the user should be redirected to, regardless of if he was or not in the past. 

Please open a new issue if you think there're additional issues related to this.
